

version: '2'

services:
  web:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/python:3.7
    command: "sh -c 'pip install -r requirements.txt && python server.py'"
    ports:
      - 8000:5000
    volumes:
      - ./web:/app

